log:
  level: DEBUG
  filePath: /logs/traefik.log
  format: json

accessLog:
  filePath: /logs/traefik.log
  format: json

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: letsencrypt@___domaine___
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
